-- 1. Favorites Table
-- This table links users to the products they have favorited.
CREATE TABLE favorites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  UNIQUE(user_id, product_id) -- Ensures a user can only favorite a product once
);

-- Comments for favorites table
COMMENT ON TABLE favorites IS 'Stores which user has favorited which product.';
COMMENT ON COLUMN favorites.user_id IS 'Reference to the user in profiles.';
COMMENT ON COLUMN favorites.product_id IS 'Reference to the product in products.';


-- 2. Set up Row Level Security (RLS) for favorites
ALTER TABLE favorites ENABLE ROW LEVEL SECURITY;

-- 3. RLS Policies for Favorites
CREATE POLICY "Users can view their own favorites."
ON favorites FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own favorites."
ON favorites FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own favorites."
ON favorites FOR DELETE
USING (auth.uid() = user_id);
