-- contactsテーブルの作成
CREATE TABLE contacts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    name text,
    email text,
    subject text,
    message text,
    is_read boolean NOT NULL DEFAULT false
);

-- contactsテーブルのRLSを有効化
ALTER TABLE contacts ENABLE ROW LEVEL SECURITY;

-- 管理者のみがcontactsテーブルを操作できるポリシー
CREATE POLICY "Allow admin to manage contacts"
ON contacts
FOR ALL
TO authenticated
USING (public.is_claims_admin())
WITH CHECK (public.is_claims_admin());
