-- 1. Favorites Table
CREATE TABLE IF NOT EXISTS favorites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  UNIQUE(user_id, product_id) -- Ensures a user can only favorite a product once
);

-- 2. Set up Row Level Security (RLS) for favorites
ALTER TABLE favorites ENABLE ROW LEVEL SECURITY;

-- 3. RLS Policies for Favorites
DROP POLICY IF EXISTS "Users can view their own favorites." ON favorites;
CREATE POLICY "Users can view their own favorites."
ON favorites FOR SELECT
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert their own favorites." ON favorites;
CREATE POLICY "Users can insert their own favorites."
ON favorites FOR INSERT
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own favorites." ON favorites;
CREATE POLICY "Users can delete their own favorites."
ON favorites FOR DELETE
USING (auth.uid() = user_id);