-- Create contacts table
CREATE TABLE IF NOT EXISTS public.contacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  name TEXT,
  email TEXT,
  subject TEXT,
  message TEXT,
  is_read BOOLEAN DEFAULT false
);

-- Add comments for the new columns
COMMENT ON TABLE public.contacts IS 'Stores contact form submissions.';
COMMENT ON COLUMN public.contacts.is_read IS 'Indicates if the contact message has been read by an admin.';

-- RLS Policies for contacts table
ALTER TABLE public.contacts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow admin full access to contacts" ON public.contacts;
CREATE POLICY "Allow admin full access to contacts"
ON public.contacts
FOR ALL
USING (public.is_claims_admin())
WITH CHECK (public.is_claims_admin());